// This file is automatically generated. Do not edit it directly.
// MODIFIED FOR LOCAL DEVELOPMENT: This file has been updated to use environment variables for Supabase keys.
// If Lovable regenerates this file, you may need to reapply these changes or configure keys via Lovable.

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prioritize environment variables, but fall back to the hardcoded values
// to ensure the application can still run if .env is not configured (e.g., in some CI/CD or if original setup is preferred).
const SUPABASE_URL_ENV = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY_ENV = import.meta.env.VITE_SUPABASE_ANON_KEY;

const SUPABASE_URL_FALLBACK = "https://hgunnubcxkzcpzutsagn.supabase.co";
const SUPABASE_KEY_FALLBACK = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhndW5udWJjeGt6Y3B6dXRzYWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODA3MjIsImV4cCI6MjA1NDI1NjcyMn0.En-J-VHrzibCBBLsElmayl8VLFPPsyHiIl5bjw6PGz4";

const SUPABASE_URL = SUPABASE_URL_ENV || SUPABASE_URL_FALLBACK;
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_KEY_ENV || SUPABASE_KEY_FALLBACK;

if (!SUPABASE_URL_ENV || !SUPABASE_KEY_ENV) {
  console.warn(
    "Supabase environment variables (VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY) are not set. " +
    "Falling back to hardcoded values. For local development, consider creating a .env file. " +
    "If this is a deployed environment, ensure variables are configured."
  );
}

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // This case should ideally not be reached if fallbacks are correctly defined.
  // If it is, it means fallbacks are also missing, which is a critical configuration error.
  console.error(
    "CRITICAL: Supabase URL or Publishable Key is definitively missing. Application may not function."
  );
  // Optionally, throw an error to prevent the app from running without any config
  // throw new Error("Supabase URL or Publishable Key is missing.");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);