// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgunnubcxkzcpzutsagn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhndW5udWJjeGt6Y3B6dXRzYWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODA3MjIsImV4cCI6MjA1NDI1NjcyMn0.En-J-VHrzibCBBLsElmayl8VLFPPsyHiIl5bjw6PGz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);